"""add username to users

Revision ID: 58095f81e57d
Revises: f1cc3dffc871
Create Date: 2026-08-06 08:22:09.811655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58095f81e57d'
down_revision: Union[str, None] = 'f1cc3dffc871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('voice_notes', sa.Column('title', sa.String(), nullable=True))
    op.add_column('voice_notes', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('voice_notes', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_notes', 'image_path')
    op.drop_column('voice_notes', 'note')
    op.drop_column('voice_notes', 'title')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
