"""add feedback to voice_notes

Revision ID: 6e951ff8c0d9
Revises: 270b1cdd5960
Create Date: 2026-08-10 07:40:21.511590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e951ff8c0d9'
down_revision: Union[str, None] = '270b1cdd5960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_notes', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_notes', 'feedback')
    # ### end Alembic commands ###
