"""add transcript_raw to voice_notes

Revision ID: 7cb28488fa58
Revises: 64553d71d3a2
Create Date: 2026-08-24 07:56:17.410074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb28488fa58'
down_revision: Union[str, None] = '64553d71d3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_notes', sa.Column('transcript_raw', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_notes', 'transcript_raw')
    # ### end Alembic commands ###
