"""add language support to insights and feedback

Revision ID: 881dff357d01
Revises: f08b5cb22a08
Create Date: 2026-08-26 20:21:30.752148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881dff357d01'
down_revision: Union[str, None] = 'f08b5cb22a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_insights', sa.Column('language', sa.String(), server_default='fa', nullable=False))
    op.drop_constraint('uq_monthly_insight_user_month', 'monthly_insights', type_='unique')
    op.create_unique_constraint('uq_monthly_insight_user_month_lang', 'monthly_insights', ['user_id', 'jalali_year', 'jalali_month', 'language'])
    op.add_column('voice_notes', sa.Column('feedback_language', sa.String(), nullable=True))
    op.add_column('weekly_insights', sa.Column('language', sa.String(), server_default='fa', nullable=False))
    op.drop_constraint('uq_weekly_insight_user_week', 'weekly_insights', type_='unique')
    op.create_unique_constraint('uq_weekly_insight_user_week_lang', 'weekly_insights', ['user_id', 'week_start', 'language'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_weekly_insight_user_week_lang', 'weekly_insights', type_='unique')
    op.create_unique_constraint('uq_weekly_insight_user_week', 'weekly_insights', ['user_id', 'week_start'])
    op.drop_column('weekly_insights', 'language')
    op.drop_column('voice_notes', 'feedback_language')
    op.drop_constraint('uq_monthly_insight_user_month_lang', 'monthly_insights', type_='unique')
    op.create_unique_constraint('uq_monthly_insight_user_month', 'monthly_insights', ['user_id', 'jalali_year', 'jalali_month'])
    op.drop_column('monthly_insights', 'language')
    # ### end Alembic commands ###
