"""add duration_seconds to voice_notes

Revision ID: af51d7a709a2
Revises: 6e951ff8c0d9
Create Date: 2026-08-10 07:59:10.469301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af51d7a709a2'
down_revision: Union[str, None] = '6e951ff8c0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_notes', sa.Column('duration_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_notes', 'duration_seconds')
    # ### end Alembic commands ###
