"""add snapshot fields to insight tables for staleness detection

Revision ID: e0d6b3db7700
Revises: 881dff357d01
Create Date: 2026-09-04 11:38:38.821243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d6b3db7700'
down_revision: Union[str, None] = '881dff357d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_insights', sa.Column('snapshot_notes_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('monthly_insights', sa.Column('snapshot_anger', sa.Float(), server_default='0', nullable=False))
    op.add_column('monthly_insights', sa.Column('snapshot_happiness', sa.Float(), server_default='0', nullable=False))
    op.add_column('monthly_insights', sa.Column('snapshot_sadness', sa.Float(), server_default='0', nullable=False))
    op.add_column('monthly_insights', sa.Column('snapshot_neutral', sa.Float(), server_default='0', nullable=False))
    op.add_column('weekly_insights', sa.Column('snapshot_notes_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('weekly_insights', sa.Column('snapshot_anger', sa.Float(), server_default='0', nullable=False))
    op.add_column('weekly_insights', sa.Column('snapshot_happiness', sa.Float(), server_default='0', nullable=False))
    op.add_column('weekly_insights', sa.Column('snapshot_sadness', sa.Float(), server_default='0', nullable=False))
    op.add_column('weekly_insights', sa.Column('snapshot_neutral', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_insights', 'snapshot_neutral')
    op.drop_column('weekly_insights', 'snapshot_sadness')
    op.drop_column('weekly_insights', 'snapshot_happiness')
    op.drop_column('weekly_insights', 'snapshot_anger')
    op.drop_column('weekly_insights', 'snapshot_notes_count')
    op.drop_column('monthly_insights', 'snapshot_neutral')
    op.drop_column('monthly_insights', 'snapshot_sadness')
    op.drop_column('monthly_insights', 'snapshot_happiness')
    op.drop_column('monthly_insights', 'snapshot_anger')
    op.drop_column('monthly_insights', 'snapshot_notes_count')
    # ### end Alembic commands ###
